### ISSUE TITLE
Validation fails with factory service "public" set to `false`

### ISSUE THREAD

**Issue by bekh6ex** [matthiasnoback/symfony-service-definition-validator#33]
Edited your test examples to reproduce the error:

``` yml
services:
    service_created_by_nonpublic_factory:
        class: stdClass
        factory: ["@nonpublic_factory", "create"]
        arguments:
            - required_argument

    nonpublic_factory:
        class: Matthias\SymfonyServiceDefinitionValidator\Tests\Functional\Fixtures\Factory
        public: false
```

Error description:

```
Object of class Symfony\Component\DependencyInjection\Definition could not be converted to string
 /var/www/html/vendor/matthiasnoback/symfony-service-definition-validator/ServiceDefinitionValidator.php:99
 /var/www/html/vendor/matthiasnoback/symfony-service-definition-validator/ServiceDefinitionValidator.php:43
 /var/www/html/vendor/matthiasnoback/symfony-service-definition-validator/ServiceDefinitionValidator.php:32
 /var/www/html/vendor/matthiasnoback/symfony-service-definition-validator/BatchServiceDefinitionValidator.php:28
 /var/www/html/vendor/matthiasnoback/symfony-service-definition-validator/Compiler/ValidateServiceDefinitionsPass.php:35
```

Versions:
- PHP: 7.0.7
- symfony/symfony: v3.1.0

**Comment by bekh6ex** [comment]
I guess there is wrong definition in `reported_problems_pre_symfony_3_0.yml`
```yml
    private_factory:
        class: Matthias\SymfonyServiceDefinitionValidator\Tests\Functional\Fixtures\Factory
        private: true
```
should be
```yml
    private_factory:
        class: Matthias\SymfonyServiceDefinitionValidator\Tests\Functional\Fixtures\Factory
        public: false
```
