### ISSUE TITLE
Factory and interface

### ISSUE THREAD

**Issue by hpatoio** [matthiasnoback/symfony-service-definition-validator#38]
I've a service with this definition

```
    foo.my.service:
        class: Foo\Api\Security\MyService
        arguments: ["@foo_posts.repository"]
```

The constructor for `Foo\Api\Security\MyService` is 

```
    public function __construct(UserContentProviderInterface $postRepository)
    {
        $this->postRepository = $postRepository;
    }
```

The service `foo_posts.repository` is defined as 

```
    foo_posts.repository:
        class: Doctrine\ORM\EntityRepository
        factory: ['@doctrine.orm.default_entity_manager', getRepository]
        arguments:
            - Foo\PostBundle\Entity\Post
```

`Foo\PostBundle\Entity\Post` looks like
 
```
/**
 * Class Post.
 * @ORM\Entity(repositoryClass="Foo\PostBundle\Repository\PostRepository")
 */
class Post
{
```
And the `PostRepository` implements `UserContentProviderInterface`

```
class PostRepository extends EntityRepository implements UserContentProviderInterface
```

The validator fails with the message 

```
Service definition validation errors (1):
- foo.my.service: Argument for type-hint "UserContentProviderInterface" points to a service of class "Doctrine\ORM\EntityRepository"
```

Is this a limit of the validator or am I doing something wrong?
