### ISSUE TITLE
pdo: Definition has no argument for required parameter PDO

### ISSUE THREAD

**Issue by cordoval** [matthiasnoback/symfony-service-definition-validator#8]
I think i have ran into a bug with:

```
   pdo:
       class: PDO
       arguments:
           dsn: "mysql:dbname=%database_name%;host=%database_host%"
           user: %database_user%
           password: %database_password%
       calls:
           - [setAttribute, [3, 2]] # \PDO::ATTR_ERRMODE, \PDO::ERRMODE_EXCEPTION
```

It always complains about a non existent argument:

```
~ php app/console                                                                                                               [Matthias\SymfonyServiceDefinitionValidator\Exception\InvalidServiceDefinitionsException]
  Service definition validation errors (1):
  - pdo: Definition has no argument for required parameter PDO
```
